
-- ============================================================================
-- Stage 2 (Brand Voice) → Tasks migration
-- ============================================================================

-- 1. Update brand_voice journey templates to 3 items (launch + growth)
UPDATE public.journey_templates
SET checklist = '[
  {"key":"brand_voice.document_generated","label":"Brand voice document generated by Claude","owner":"auto","auto_key":"brand_voice_generated","done":false},
  {"key":"brand_voice.review_and_approve","label":"Review and approve document","owner":"agency","done":false},
  {"key":"brand_voice.sent_to_client","label":"Brand voice sent to client for review","owner":"auto","done":false}
]'::jsonb
WHERE key = 'brand_voice';

-- 2. Re-shape existing brand_voice journey_nodes checklists, preserving "done" state.
DO $$
DECLARE
  r record;
  was_gen boolean;
  was_review boolean;
  was_sent boolean;
  c_pdf text;
  c_approved boolean;
  c_brand_kit_at timestamptz;
BEGIN
  FOR r IN
    SELECT jn.id, jn.client_id, jn.checklist
      FROM public.journey_nodes jn
     WHERE jn.key = 'brand_voice'
  LOOP
    SELECT
      bool_or(item->>'key' IN ('brand_voice.document_generated',
                               'brand_voice.brand_voice_generated',
                               'brand_voice.brand_voice_pdf',
                               'brand_voice.brand_voice_qrc')
              AND coalesce((item->>'done')::boolean, false)),
      bool_or(item->>'key' IN ('brand_voice.review_and_approve',
                               'brand_voice.review_and_approve_document')
              AND coalesce((item->>'done')::boolean, false)),
      bool_or(item->>'key' IN ('brand_voice.sent_to_client',
                               'brand_voice.client_portal_link_sent_brand_kit_intake_ready')
              AND coalesce((item->>'done')::boolean, false))
    INTO was_gen, was_review, was_sent
    FROM jsonb_array_elements(coalesce(r.checklist, '[]'::jsonb)) item;

    SELECT brand_voice_pdf_path, brand_voice_approved, brand_kit_intake_submitted_at
      INTO c_pdf, c_approved, c_brand_kit_at
      FROM public.clients WHERE id = r.client_id;

    UPDATE public.journey_nodes
       SET checklist = jsonb_build_array(
         jsonb_build_object('key','brand_voice.document_generated',
                            'label','Brand voice document generated by Claude',
                            'owner','auto','auto_key','brand_voice_generated',
                            'done', coalesce(was_gen,false) OR c_pdf IS NOT NULL),
         jsonb_build_object('key','brand_voice.review_and_approve',
                            'label','Review and approve document',
                            'owner','agency',
                            'done', coalesce(was_review,false) OR coalesce(c_approved,false)),
         jsonb_build_object('key','brand_voice.sent_to_client',
                            'label','Brand voice sent to client for review',
                            'owner','auto',
                            'done', coalesce(was_sent,false) OR c_brand_kit_at IS NOT NULL)
       )
     WHERE id = r.id;
  END LOOP;
END $$;

-- 3. ensure_brand_voice_tasks_for_project
CREATE OR REPLACE FUNCTION public.ensure_brand_voice_tasks_for_project(_client_project_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_client_id uuid; v_node_id uuid; v_epic_id uuid; v_checklist jsonb; v_item jsonb;
  v_idx int := 0; v_done boolean;
  v_status project_task_status; v_assignee project_task_assignee_kind;
  v_pdf_url text; v_pdf_path text;
BEGIN
  SELECT client_id INTO v_client_id FROM public.client_projects WHERE id = _client_project_id;
  IF v_client_id IS NULL THEN RETURN; END IF;

  SELECT id, checklist INTO v_node_id, v_checklist
    FROM public.journey_nodes
   WHERE client_project_id = _client_project_id AND key = 'brand_voice' LIMIT 1;
  IF v_node_id IS NULL THEN RETURN; END IF;

  SELECT brand_voice_pdf_url, brand_voice_pdf_path
    INTO v_pdf_url, v_pdf_path FROM public.clients WHERE id = v_client_id;

  SELECT id INTO v_epic_id FROM public.project_task_epics
   WHERE client_project_id = _client_project_id AND journey_stage_key = 'brand_voice' LIMIT 1;
  IF v_epic_id IS NULL THEN
    INSERT INTO public.project_task_epics (client_project_id, name, order_index, journey_stage_key)
      VALUES (_client_project_id, '2. Brand Voice', 1, 'brand_voice') RETURNING id INTO v_epic_id;
  ELSE
    UPDATE public.project_task_epics SET name = '2. Brand Voice', order_index = 1 WHERE id = v_epic_id;
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(coalesce(v_checklist, '[]'::jsonb))
  LOOP
    v_done := coalesce((v_item->>'done')::boolean, false);
    v_status := CASE WHEN v_done THEN 'complete'::project_task_status ELSE 'backlog'::project_task_status END;
    v_assignee := CASE coalesce(v_item->>'owner', 'unassigned')
                    WHEN 'auto'   THEN 'auto'::project_task_assignee_kind
                    WHEN 'client' THEN 'client'::project_task_assignee_kind
                    WHEN 'agency' THEN 'agency'::project_task_assignee_kind
                    ELSE 'unassigned'::project_task_assignee_kind
                  END;

    IF EXISTS (
      SELECT 1 FROM public.project_tasks
       WHERE client_project_id = _client_project_id AND journey_item_key = v_item->>'key'
    ) THEN
      UPDATE public.project_tasks pt
         SET name = v_item->>'label',
             epic_id = v_epic_id,
             assignee_kind = v_assignee,
             order_index = v_idx,
             auto_key = v_item->>'auto_key',
             url = CASE
               WHEN v_item->>'key' = 'brand_voice.document_generated'
                 THEN coalesce(pt.url, v_pdf_url)
               ELSE pt.url END,
             status = CASE
               WHEN v_done THEN 'complete'::project_task_status
               WHEN pt.status = 'complete' THEN 'backlog'::project_task_status
               ELSE pt.status END,
             completed_at = CASE WHEN v_done THEN coalesce(pt.completed_at, now()) ELSE NULL END
       WHERE pt.client_project_id = _client_project_id AND pt.journey_item_key = v_item->>'key';
    ELSE
      INSERT INTO public.project_tasks
        (client_project_id, epic_id, name, status, assignee_kind, order_index,
         journey_item_key, auto_key, url, completed_at)
      VALUES
        (_client_project_id, v_epic_id, v_item->>'label', v_status, v_assignee, v_idx,
         v_item->>'key', v_item->>'auto_key',
         CASE WHEN v_item->>'key' = 'brand_voice.document_generated' THEN v_pdf_url ELSE NULL END,
         CASE WHEN v_done THEN now() ELSE NULL END);
    END IF;

    v_idx := v_idx + 1;
  END LOOP;

  -- Attach PDF (if present and not already attached) to the document_generated task
  IF v_pdf_path IS NOT NULL THEN
    INSERT INTO public.project_task_attachments (task_id, storage_path, file_name, mime_type)
    SELECT pt.id, v_pdf_path,
           substring(v_pdf_path from '[^/]+$'),
           'application/pdf'
      FROM public.project_tasks pt
     WHERE pt.client_project_id = _client_project_id
       AND pt.journey_item_key = 'brand_voice.document_generated'
       AND NOT EXISTS (
         SELECT 1 FROM public.project_task_attachments a
          WHERE a.task_id = pt.id AND a.storage_path = v_pdf_path
       );
  END IF;
END;
$$;

-- 4. Generalize the journey-node insert trigger to dispatch by key.
DROP TRIGGER IF EXISTS trg_ensure_intake_tasks_on_node_insert ON public.journey_nodes;

CREATE OR REPLACE FUNCTION public.ensure_stage_tasks_on_node_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.client_project_id IS NULL THEN RETURN NEW; END IF;
  IF NEW.key = 'intake' THEN
    PERFORM public.ensure_intake_tasks_for_project(NEW.client_project_id);
  ELSIF NEW.key = 'brand_voice' THEN
    PERFORM public.ensure_brand_voice_tasks_for_project(NEW.client_project_id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_ensure_stage_tasks_on_node_insert
AFTER INSERT ON public.journey_nodes
FOR EACH ROW EXECUTE FUNCTION public.ensure_stage_tasks_on_node_insert();

-- 5. Bidirectional sync — brand_voice variant of the intake sync triggers.
CREATE OR REPLACE FUNCTION public.sync_brand_voice_tasks_from_journey()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_item jsonb; v_done boolean; v_key text;
BEGIN
  IF NEW.key <> 'brand_voice' OR NEW.client_project_id IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.checklist IS NOT DISTINCT FROM OLD.checklist THEN RETURN NEW; END IF;

  PERFORM public.ensure_brand_voice_tasks_for_project(NEW.client_project_id);

  FOR v_item IN SELECT * FROM jsonb_array_elements(coalesce(NEW.checklist, '[]'::jsonb))
  LOOP
    v_key := v_item->>'key';
    v_done := coalesce((v_item->>'done')::boolean, false);
    UPDATE public.project_tasks pt
       SET status = CASE
             WHEN v_done THEN 'complete'::project_task_status
             WHEN pt.status = 'complete' THEN 'backlog'::project_task_status
             ELSE pt.status END,
           completed_at = CASE WHEN v_done THEN coalesce(pt.completed_at, now()) ELSE NULL END
     WHERE pt.client_project_id = NEW.client_project_id
       AND pt.journey_item_key = v_key
       AND ((v_done AND pt.status <> 'complete') OR (NOT v_done AND pt.status = 'complete'));
  END LOOP;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sync_brand_voice_tasks_from_journey
AFTER INSERT OR UPDATE ON public.journey_nodes
FOR EACH ROW EXECUTE FUNCTION public.sync_brand_voice_tasks_from_journey();

CREATE OR REPLACE FUNCTION public.sync_brand_voice_journey_from_task()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_new_done boolean; v_node_checklist jsonb; v_updated jsonb; v_item_done boolean;
  v_client_id uuid;
BEGIN
  IF NEW.journey_item_key IS NULL OR NEW.journey_item_key NOT LIKE 'brand_voice.%' THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;

  v_new_done := (NEW.status = 'complete');

  SELECT checklist INTO v_node_checklist
    FROM public.journey_nodes
   WHERE client_project_id = NEW.client_project_id AND key = 'brand_voice'
   FOR UPDATE;
  IF v_node_checklist IS NULL THEN RETURN NEW; END IF;

  SELECT coalesce((item->>'done')::boolean, false) INTO v_item_done
    FROM jsonb_array_elements(v_node_checklist) item
   WHERE item->>'key' = NEW.journey_item_key LIMIT 1;

  IF v_item_done IS DISTINCT FROM v_new_done THEN
    SELECT jsonb_agg(
             CASE WHEN item->>'key' = NEW.journey_item_key
                  THEN item || jsonb_build_object('done', v_new_done)
                  ELSE item END)
      INTO v_updated FROM jsonb_array_elements(v_node_checklist) item;

    UPDATE public.journey_nodes
       SET checklist = v_updated, updated_at = now()
     WHERE client_project_id = NEW.client_project_id AND key = 'brand_voice';
  END IF;

  -- Side effects on review_and_approve completion:
  IF NEW.journey_item_key = 'brand_voice.review_and_approve' AND v_new_done THEN
    SELECT client_id INTO v_client_id FROM public.client_projects WHERE id = NEW.client_project_id;
    IF v_client_id IS NOT NULL THEN
      UPDATE public.clients
         SET brand_voice_approved = true,
             brand_voice_approved_at = coalesce(brand_voice_approved_at, now())
       WHERE id = v_client_id;
    END IF;
    -- Auto-complete the sent_to_client task (mirrors via the journey trigger above).
    UPDATE public.project_tasks
       SET status = 'complete'::project_task_status,
           completed_at = coalesce(completed_at, now())
     WHERE client_project_id = NEW.client_project_id
       AND journey_item_key = 'brand_voice.sent_to_client'
       AND status <> 'complete';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sync_brand_voice_journey_from_task
AFTER INSERT OR UPDATE ON public.project_tasks
FOR EACH ROW EXECUTE FUNCTION public.sync_brand_voice_journey_from_task();

-- 6. Backfill brand_voice tasks for all automation_build projects.
DO $$
DECLARE p record;
BEGIN
  FOR p IN
    SELECT cp.id FROM public.client_projects cp
      JOIN public.journey_nodes jn ON jn.client_project_id = cp.id AND jn.key = 'brand_voice'
     WHERE cp.type = 'automation_build'
  LOOP
    PERFORM public.ensure_brand_voice_tasks_for_project(p.id);
  END LOOP;
END $$;
