
-- 1. Add checklist columns
ALTER TABLE public.journey_templates
  ADD COLUMN IF NOT EXISTS checklist jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.journey_nodes
  ADD COLUMN IF NOT EXISTS checklist jsonb NOT NULL DEFAULT '[]'::jsonb;

-- 2. Seed templates (Growth + Launch)
-- Owner values: 'auto' | 'client' | 'agency'
-- Each item: { "id": "<stable-key>", "label": "...", "owner": "auto|client|agency", "done": false, "auto_key": "optional-system-trigger-key" }

-- ===== GROWTH TIER =====
UPDATE public.journey_templates SET checklist = '[
  {"id":"g-intake-1","label":"Onboarding chat completed","owner":"auto","done":false,"auto_key":"onboarding_completed"},
  {"id":"g-intake-2","label":"Client record created in Supabase","owner":"auto","done":false,"auto_key":"client_created"},
  {"id":"g-intake-3","label":"Pipeline nodes generated","owner":"auto","done":false,"auto_key":"nodes_seeded"},
  {"id":"g-intake-4","label":"Welcome sequence enrolled in SureContact","owner":"auto","done":false},
  {"id":"g-intake-5","label":"Brand voice generation triggered","owner":"auto","done":false,"auto_key":"brand_voice_triggered"}
]'::jsonb WHERE tier='growth' AND key='intake';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-bv-1","label":"Brand voice document generated by Claude","owner":"auto","done":false,"auto_key":"brand_voice_generated"},
  {"id":"g-bv-2","label":"Quick Reference Card extracted","owner":"auto","done":false,"auto_key":"brand_voice_qrc"},
  {"id":"g-bv-3","label":"PDF saved to Supabase storage","owner":"auto","done":false,"auto_key":"brand_voice_pdf"},
  {"id":"g-bv-4","label":"Review and approve document","owner":"agency","done":false},
  {"id":"g-bv-5","label":"Client portal link sent — Brand Kit intake ready","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='brand_voice';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-bk-1","label":"Portal link generated and sent to client","owner":"auto","done":false},
  {"id":"g-bk-2","label":"Logos submitted","owner":"client","done":false,"auto_key":"brand_kit_logos"},
  {"id":"g-bk-3","label":"Color palette submitted","owner":"client","done":false,"auto_key":"brand_kit_colors"},
  {"id":"g-bk-4","label":"Typography submitted","owner":"client","done":false,"auto_key":"brand_kit_typography"},
  {"id":"g-bk-5","label":"Visual references submitted","owner":"client","done":false,"auto_key":"brand_kit_references"},
  {"id":"g-bk-6","label":"Brand guidelines submitted","owner":"client","done":false,"auto_key":"brand_kit_guidelines"},
  {"id":"g-bk-7","label":"Build brand kit using Claude Design","owner":"agency","done":false},
  {"id":"g-bk-8","label":"Send brand kit to client for approval","owner":"agency","done":false},
  {"id":"g-bk-9","label":"Brand kit approved","owner":"client","done":false},
  {"id":"g-bk-10","label":"Brand kit PDF saved to Supabase","owner":"auto","done":false},
  {"id":"g-bk-11","label":"Brain Setup node unlocked","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='brand_kit';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-bs-1","label":"Create Claude Project for client","owner":"agency","done":false},
  {"id":"g-bs-2","label":"Paste project instructions and Quick Reference Card","owner":"agency","done":false},
  {"id":"g-bs-3","label":"Brand voice doc uploaded to project","owner":"auto","done":false},
  {"id":"g-bs-4","label":"Brand kit uploaded to project","owner":"auto","done":false},
  {"id":"g-bs-5","label":"Generate and upload Ideal Customer Profile","owner":"agency","done":false},
  {"id":"g-bs-6","label":"Generate and upload Offer Suite","owner":"agency","done":false},
  {"id":"g-bs-7","label":"Build Lead Intake SOP","owner":"agency","done":false},
  {"id":"g-bs-8","label":"Build Client Onboarding SOP","owner":"agency","done":false},
  {"id":"g-bs-9","label":"Build Content Creation SOP","owner":"agency","done":false},
  {"id":"g-bs-10","label":"Build Weekly Review Checklist","owner":"agency","done":false},
  {"id":"g-bs-11","label":"Build Pricing Decision Guide","owner":"agency","done":false},
  {"id":"g-bs-12","label":"Upload all 5 skill files","owner":"agency","done":false},
  {"id":"g-bs-13","label":"Run 3 test prompts and confirm Brain working","owner":"agency","done":false},
  {"id":"g-bs-14","label":"Share Claude Project with client","owner":"agency","done":false},
  {"id":"g-bs-15","label":"Claude Project URL saved to client record","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='brain_setup';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-a1-1","label":"Inquiry channel pulled from intake data","owner":"auto","done":false},
  {"id":"g-a1-2","label":"Connect inquiry channel to SureContact via Ottokit","owner":"agency","done":false},
  {"id":"g-a1-3","label":"Build AI lead response in client brand voice","owner":"agency","done":false},
  {"id":"g-a1-4","label":"Build follow-up sequence in SureContact","owner":"agency","done":false},
  {"id":"g-a1-5","label":"Build onboarding sequence in SureContact","owner":"agency","done":false},
  {"id":"g-a1-6","label":"Test full flow with dummy inquiry","owner":"agency","done":false},
  {"id":"g-a1-7","label":"Ottokit workflow URL saved to node","owner":"auto","done":false},
  {"id":"g-a1-8","label":"SureContact sequence name saved to node","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='automation_01';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-av-1","label":"Portal link sent and avatar instructions delivered to client","owner":"auto","done":false},
  {"id":"g-av-2","label":"Video footage submitted or stock avatar selected","owner":"client","done":false},
  {"id":"g-av-3","label":"Upload footage to HeyGen","owner":"agency","done":false},
  {"id":"g-av-4","label":"Build avatar in HeyGen account","owner":"agency","done":false},
  {"id":"g-av-5","label":"Test avatar with sample script","owner":"agency","done":false},
  {"id":"g-av-6","label":"Approve avatar quality","owner":"agency","done":false},
  {"id":"g-av-7","label":"Avatar ID saved to client record","owner":"auto","done":false},
  {"id":"g-av-8","label":"Avatar connected to Content System workflow","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='avatar';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-a2-1","label":"Set up client content inbox","owner":"agency","done":false},
  {"id":"g-a2-2","label":"Build Ottokit content publishing workflow","owner":"agency","done":false},
  {"id":"g-a2-3","label":"Connect to client social platforms","owner":"agency","done":false},
  {"id":"g-a2-4","label":"Load first month of content prompts","owner":"agency","done":false},
  {"id":"g-a2-5","label":"Test with dummy content drop","owner":"agency","done":false},
  {"id":"g-a2-6","label":"Content inbox channel saved to node","owner":"auto","done":false},
  {"id":"g-a2-7","label":"Platforms confirmed and saved","owner":"auto","done":false},
  {"id":"g-a2-8","label":"Ottokit workflow URL saved to node","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='automation_02';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-cs-1","label":"Build Ottokit reel production workflow","owner":"agency","done":false},
  {"id":"g-cs-2","label":"Connect HeyGen avatar to workflow","owner":"agency","done":false},
  {"id":"g-cs-3","label":"Build SureContact script approval email","owner":"agency","done":false},
  {"id":"g-cs-4","label":"Test full reel flow from idea to published video","owner":"agency","done":false},
  {"id":"g-cs-5","label":"First reel script generated and sent for approval","owner":"auto","done":false},
  {"id":"g-cs-6","label":"First reel script approved","owner":"client","done":false},
  {"id":"g-cs-7","label":"First reel rendered by HeyGen","owner":"auto","done":false},
  {"id":"g-cs-8","label":"Content log table updated in Supabase","owner":"auto","done":false}
]'::jsonb WHERE tier='growth' AND key='content_system';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-del-1","label":"Record Loom walkthrough 12 to 18 minutes","owner":"agency","done":false},
  {"id":"g-del-2","label":"Paste Loom URL into dashboard","owner":"agency","done":false},
  {"id":"g-del-3","label":"Delivery email fired via SureContact Cre8 Visions account","owner":"auto","done":false},
  {"id":"g-del-4","label":"All asset links included in delivery email","owner":"auto","done":false},
  {"id":"g-del-5","label":"Active node unlocked","owner":"auto","done":false},
  {"id":"g-del-6","label":"Delivery confirmed received","owner":"client","done":false}
]'::jsonb WHERE tier='growth' AND key='delivery';

UPDATE public.journey_templates SET checklist = '[
  {"id":"g-act-1","label":"Monthly cycle triggered 1st of month","owner":"auto","done":false},
  {"id":"g-act-2","label":"Monthly delivery log entry created","owner":"auto","done":false},
  {"id":"g-act-3","label":"AI assistant updated","owner":"agency","done":false},
  {"id":"g-act-4","label":"Content prompt refresh sent to client","owner":"auto","done":false},
  {"id":"g-act-5","label":"Strategy briefing sent via SureContact","owner":"auto","done":false},
  {"id":"g-act-6","label":"Monthly summary email sent to client","owner":"auto","done":false},
  {"id":"g-act-7","label":"Log monthly update in dashboard","owner":"agency","done":false}
]'::jsonb WHERE tier='growth' AND key='active';

-- ===== LAUNCH TIER (subset of growth, same items where the node names match) =====
UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='intake'
) WHERE tier='launch' AND key='intake';

UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='brand_voice'
) WHERE tier='launch' AND key='brand_voice';

UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='automation_01'
) WHERE tier='launch' AND key='automation_01';

UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='automation_02'
) WHERE tier='launch' AND key='automation_02';

UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='delivery'
) WHERE tier='launch' AND key='delivery';

UPDATE public.journey_templates SET checklist = (
  SELECT checklist FROM public.journey_templates WHERE tier='growth' AND key='active'
) WHERE tier='launch' AND key='active';

-- 3. Update seed trigger to copy checklist onto new journey nodes
CREATE OR REPLACE FUNCTION public.seed_journey_nodes_for_client()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.journey_nodes (client_id, template_id, key, label, order_index, checklist)
  SELECT NEW.id, t.id, t.key, t.label, t.order_index, t.checklist
  FROM public.journey_templates t
  WHERE t.tier = NEW.tier
  ON CONFLICT (client_id, key) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_journey_nodes_on_tier_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF NEW.tier IS DISTINCT FROM OLD.tier THEN
    INSERT INTO public.journey_nodes (client_id, template_id, key, label, order_index, checklist)
    SELECT NEW.id, t.id, t.key, t.label, t.order_index, t.checklist
    FROM public.journey_templates t
    WHERE t.tier = NEW.tier
    ON CONFLICT (client_id, key) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$function$;

-- 4. Auto-complete + auto-advance trigger
CREATE OR REPLACE FUNCTION public.auto_complete_journey_node()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  total_items int;
  done_items int;
  next_node_id uuid;
BEGIN
  -- Only act when checklist actually changed
  IF NEW.checklist IS NOT DISTINCT FROM OLD.checklist THEN
    RETURN NEW;
  END IF;

  total_items := jsonb_array_length(COALESCE(NEW.checklist, '[]'::jsonb));
  IF total_items = 0 THEN
    RETURN NEW;
  END IF;

  SELECT count(*) INTO done_items
  FROM jsonb_array_elements(NEW.checklist) item
  WHERE COALESCE((item->>'done')::boolean, false) = true;

  -- All items done → mark complete + advance next pending node to in_progress
  IF done_items = total_items AND NEW.status <> 'complete' THEN
    NEW.status := 'complete';
    NEW.completed_at := COALESCE(NEW.completed_at, now());
    IF NEW.started_at IS NULL THEN NEW.started_at := now(); END IF;

    SELECT id INTO next_node_id
    FROM public.journey_nodes
    WHERE client_id = NEW.client_id
      AND order_index > NEW.order_index
      AND status = 'pending'
    ORDER BY order_index ASC
    LIMIT 1;

    IF next_node_id IS NOT NULL THEN
      UPDATE public.journey_nodes
      SET status = 'in_progress', started_at = COALESCE(started_at, now())
      WHERE id = next_node_id;
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS auto_complete_journey_node_trg ON public.journey_nodes;
CREATE TRIGGER auto_complete_journey_node_trg
BEFORE UPDATE ON public.journey_nodes
FOR EACH ROW EXECUTE FUNCTION public.auto_complete_journey_node();

-- Make sure the existing stamp trigger still runs
DROP TRIGGER IF EXISTS stamp_journey_node_status_trg ON public.journey_nodes;
CREATE TRIGGER stamp_journey_node_status_trg
BEFORE UPDATE ON public.journey_nodes
FOR EACH ROW EXECUTE FUNCTION public.stamp_journey_node_status();

DROP TRIGGER IF EXISTS seed_journey_nodes_trg ON public.clients;
CREATE TRIGGER seed_journey_nodes_trg
AFTER INSERT ON public.clients
FOR EACH ROW EXECUTE FUNCTION public.seed_journey_nodes_for_client();

DROP TRIGGER IF EXISTS sync_journey_nodes_on_tier_change_trg ON public.clients;
CREATE TRIGGER sync_journey_nodes_on_tier_change_trg
AFTER UPDATE ON public.clients
FOR EACH ROW EXECUTE FUNCTION public.sync_journey_nodes_on_tier_change();

-- 5. Back-fill existing journey_nodes whose checklist is empty
UPDATE public.journey_nodes n
SET checklist = t.checklist
FROM public.journey_templates t
WHERE n.template_id = t.id
  AND (n.checklist IS NULL OR jsonb_array_length(n.checklist) = 0)
  AND jsonb_array_length(t.checklist) > 0;
